// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

TestCase := TextInput {
    width: 100phx;
    height: 100phx;
    property<string> test_text: self.text;
    property<int> test_cursor_pos: self.cursor_position;
    property<int> test_anchor_pos: self.anchor_position;
    property<bool> has_selection: self.cursor_position != self.anchor_position;
    property<bool> input_focused: self.has_focus;
}

/*
```rust

const LEFT_CODE: char = '\u{F702}';

let shift_modifier = slint::private_unstable_api::re_exports::KeyboardModifiers {
    shift: true,
    ..Default::default()
};

let control_modifier = slint::private_unstable_api::re_exports::KeyboardModifiers {
    control: true,
    ..Default::default()
};

let instance = TestCase::new();
slint_testing::send_mouse_click(&instance, 50., 50.);
assert!(instance.get_input_focused());
assert_eq!(instance.get_test_text(), "");
slint_testing::send_keyboard_string_sequence(&instance, "Test");
assert_eq!(instance.get_test_text(), "Test");
assert!(!instance.get_has_selection());

slint_testing::send_keyboard_string(&instance, slint::private_unstable_api::re_exports::Key::Control.into(), true);
slint_testing::send_keyboard_string_sequence(&instance, "a");
slint_testing::send_keyboard_string(&instance, slint::private_unstable_api::re_exports::Key::Control.into(), false);
slint_testing::send_keyboard_string(&instance, slint::private_unstable_api::re_exports::Key::Shift.into(), true);
slint_testing::send_keyboard_string_sequence(&instance, &LEFT_CODE.to_string());
slint_testing::send_keyboard_string_sequence(&instance, &LEFT_CODE.to_string());
slint_testing::send_keyboard_string(&instance, slint::private_unstable_api::re_exports::Key::Shift.into(), false);
slint_testing::send_keyboard_string(&instance, slint::private_unstable_api::re_exports::Key::Control.into(), true);
slint_testing::send_keyboard_string_sequence(&instance, "x");
slint_testing::send_keyboard_string(&instance, slint::private_unstable_api::re_exports::Key::Control.into(), false);
assert!(!instance.get_has_selection());
assert_eq!(instance.get_test_text(), "st");
assert_eq!(instance.get_test_cursor_pos(), 0);
```
*/
