export Keyboard := Rectangle {
    property<string> text: "text";

    callback closed(string);

    VerticalLayout {  
        Text {  
            text  <=> root.text;
        }
        Rectangle { 
            background: blue;

            Text {
                text: "a";
                color: white;
            }

            TouchArea {  
                clicked => { text += "a"; }
            }
         }

         Rectangle { 
            background: green;

            Text {
                text: "enter"; 
                color: white;
            }

            TouchArea {  
                clicked => { closed(text); }
            }
         }
    }
}