import { TextField } from "text_field.slint";
import { KeyboardView } from "keyboard_view.slint";

export global SettingsAdapter := {
   
    property <string> user-name: "name";
    property <string> password: "password";

   

    callback update-text(string, string);

    update-text(prop, text) => { 
        if(prop == "user-name") {
            user-name = text;
        }

        if(prop == "password") {
            password = text;
        }
    } 
}

export SettingsView := KeyboardView {

    text-update(prop, text) => {
        SettingsAdapter.update-text(prop, text);
    }

   VerticalLayout {  
        width: 100%;
        height: 100%;
        spacing: 3px;

        TextField { 
            text <=> SettingsAdapter.user-name;

            open-keyboard => {  
                root.open-keyboard("user-name", text);
            }
         }

         TextField { 
            text <=> SettingsAdapter.password;
            open-keyboard => {  
                root.open-keyboard("password", text);
            }
         }
    }
}